# general settings
name: train_FSCSR_SRx2_from_scratch
model_type: FSCSRModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/UCMerced/UCMerced_HR_sub
    dataroot_lq: datasets/UCMerced/UCMerced_LRX2_sub
#    meta_info_file: drct/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend:
      type: disk

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set420
    type: PairedImageDataset
    dataroot_gt: datasets/UCMerced/UCMerced_VAL_1
    dataroot_lq: datasets/UCMerced/UCMerced_VALX2_1
    io_backend:
      type: disk

#  val_2:
#    name: Set14
#    type: PairedImageDataset
#    dataroot_gt: /work/u1657859/DRCT/datasets/Set14/GTmod12/
#    dataroot_lq: /work/u1657859/DRCT/datasets/Set14/LRbicx4/
#    io_backend:
#      type: disk

  # val_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/urban100/GTmod4
  #   dataroot_lq: ./datasets/urban100/LRbicx4
  #   io_backend:
  #     type: disk



# network structures
network_g:
  type: FSCSR
  upscale: 2
  in_chans: 3
  img_size: 48
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 150000]
    gamma: 0.5

  total_iter: 150000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 500
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
#    scc:
#      type: calculate_scc
#      crop_border: 2
#      test_y_channel: true
#      better: higher
#    lpips:
#      type: calculate_lpips
#      crop_border: 2
#      test_y_channel: true
#      better: lower


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
